### ISSUE TITLE
This is the outdated 0.7.0 version

### ISSUE THREAD

**Issue by MrRatermat** [BlkStormy/epic-inventor#4]
Please update the source to version 1.0!

**Comment by scj643** [comment]
I second this.

**Comment by MrRatermat** [comment]
I personally want the newer version because the code is lacking the Oobaboo tribe and there are too many multiplayer bugs that exist in 0.7.0 that have been fixed in 0.8.0 and 1.0

**Comment by alphaonex86** [comment]
+1

**Comment by Bejoscha** [comment]
Please update! Too nice a game to prevent proper community development.

**Comment by akien-mga** [comment]
+1, I guess nobody will start spending too much time contributing to the community development knowing that most of the current bugs are already fixed in an unpublished code version...

**Comment by Trigger2004** [comment]
+ 1

**Comment by BlkStormy** [comment]
Sorry guys, when I originally committed the source code, it was an older version and I thought I had lost the most recent files!  However, I was just able to recover some newer ones and I think this was close if not the latest version.  Just committed 1.0.1

**Comment by MrRatermat** [comment]
Fucking A*, my main man! You're a goddamn hero. Thank you!
